language: node_js
sudo: false
notifications:
  email:
    on_failure: always
    on_success: change
node_js:
  - '6'
  - '4'

matrix:
  include:
    - node_js: '6'
      env: CI_MODE=saucelabs
      addons:
        sauce_connect: true

after_success: codecov