language: node_js
sudo: false
notifications:
  email:
    on_failure: always
    on_success: change
node_js:
  - '6'
  - '4'
script: npm run ci-test
addons:
  browserstack:
    username:
      secure: "sassounderderian1"
    access_key:
      secure: "RiRAISQ1espgnPgoczTj3wlBh2GTfexfjnJhcTswhTO6TDWulwGNhltDgYDd9oVmy3p+zAh7vGakvVpEeMFv5NzUc4rN6SNBRaAPoqFa12gawHoL/UIFwsnfFdILLPoF3d8mWpqQbZ3xbd2EBndDS0/a+WifKeXPu73wqbSdLlU="
